// Code generated by Slice Machine. DO NOT EDIT.

import Banner from './Banner';
import CodeBox from './CodeBox';
import HeroBanner from './HeroBanner';
import Highlighted from './Highlighted';
import RichText from './RichText';
import SectionHeading from './SectionHeading';
import SectionPoerty from './SectionPoerty';

export {
	Banner,
	CodeBox,
	HeroBanner,
	Highlighted,
	RichText,
	SectionHeading,
	SectionPoerty,
};

export const components = {
	banner: Banner,
	code_box: CodeBox,
	hero_banner: HeroBanner,
	highlighted: Highlighted,
	rich_text: RichText,
	section_heading: SectionHeading,
	section_poerty: SectionPoerty,
};
