import * as fs from "fs";
import * as path from "path";

// Parse CSS file to extract CSS variables
function parseCssVariables(cssPath: string): Record<string, string> {
  const cssContent = fs.readFileSync(cssPath, "utf-8");
  const variables: Record<string, string> = {};

  // Extract :root block (light mode)
  const rootMatch = cssContent.match(/:root\s*\{([\s\S]+?)\}(?=\s*@media|\s*@layer|$)/);
  if (!rootMatch) {
    throw new Error("Could not find :root block in CSS file");
  }

  const rootContent = rootMatch[1];

  // Extract all CSS variable definitions
  const varRegex = /--([\w-]+):\s*([^;]+);/g;
  let match;

  while ((match = varRegex.exec(rootContent)) !== null) {
    const varName = `--${match[1]}`;
    let varValue = match[2].trim();

    // Resolve var() references
    varValue = resolveVarReference(varValue, rootContent);

    // Only include color values (hex colors)
    if (isColorValue(varValue)) {
      variables[varName] = varValue;
    }
  }

  return variables;
}

// Resolve var() references recursively
function resolveVarReference(value: string, rootContent: string, visited: Set<string> = new Set()): string {
  // Check if value contains var()
  const varMatch = value.match(/var\(([^)]+)\)/);
  if (!varMatch) {
    return value;
  }

  const referencedVar = varMatch[1].trim();
  const varName = referencedVar.startsWith("--") ? referencedVar : `--${referencedVar}`;
  
  // Prevent infinite recursion
  if (visited.has(varName)) {
    return value;
  }
  visited.add(varName);

  // Find the variable definition
  const varRegex = new RegExp(`(${varName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}):\\s*([^;]+);`);
  const refMatch = rootContent.match(varRegex);

  if (refMatch) {
    let resolvedValue = refMatch[2].trim();
    
    // If the resolved value is another var(), resolve it recursively
    if (resolvedValue.includes("var(")) {
      resolvedValue = resolveVarReference(resolvedValue, rootContent, visited);
    }
    
    // Replace var() with resolved value
    const newValue = value.replace(/var\([^)]+\)/, resolvedValue);
    // Recursively resolve if there are more var() references
    return resolveVarReference(newValue, rootContent, visited);
  }

  return value;
}

// Check if a value is a color (hex color)
function isColorValue(value: string): boolean {
  // Check for hex colors (#RRGGBB or #RRGGBBAA)
  return /^#([a-f\d]{6}|[a-f\d]{8})$/i.test(value.trim());
}

// Generate TypeScript constants file
function generateConstantsFile(
  variables: Record<string, string>,
  outputPath: string
): void {
  // Filter to only include the variables we want in constants
  const colorMap: Record<string, string> = {};

  // Add accent colors (1-12)
  for (let i = 1; i <= 12; i++) {
    const key = `--accent-${i}`;
    if (variables[key]) {
      colorMap[key] = variables[key];
    }
  }

  // Add gray colors (1-12)
  for (let i = 1; i <= 12; i++) {
    const key = `--gray-${i}`;
    if (variables[key]) {
      colorMap[key] = variables[key];
    }
  }

  // Add gray alpha colors (a1-a12)
  for (let i = 1; i <= 12; i++) {
    const key = `--gray-a${i}`;
    if (variables[key]) {
      colorMap[key] = variables[key];
    }
  }

  // Add aura-specific variables
  const auraVars = [
    "--aura-accents-primary",
    "--aura-text-primary",
    "--aura-text-primary-inverse",
    "--aura-link",
    "--aura-link-hover",
    "--aura-button-hover",
  ];

  auraVars.forEach((varName) => {
    if (variables[varName]) {
      colorMap[varName] = variables[varName];
    }
  });

  // Generate TypeScript file content
  const lines = [
    "// Color resolution map from CSS variables to actual hex values",
    "// This file is auto-generated by scripts/generate-constants.ts",
    "// Do not edit manually. Run the script to regenerate.",
    "export const colorMap: Record<string, string> = {",
  ];

  // Sort keys for consistent output
  const sortedKeys = Object.keys(colorMap).sort();

  sortedKeys.forEach((key, index) => {
    const value = colorMap[key];
    const comma = index < sortedKeys.length - 1 ? "," : "";
    lines.push(`  "${key}": "${value}"${comma}`);
  });

  lines.push("};");
  lines.push("");

  const content = lines.join("\n");

  // Write to file
  fs.writeFileSync(outputPath, content, "utf-8");
  console.log(`✅ Successfully generated ${outputPath}`);
  console.log(`   Generated ${sortedKeys.length} color mappings`);
}

// Main execution
function main() {
  const cssPath = path.resolve(__dirname, "../styles/globals.css");
  const outputPath = path.resolve(__dirname, "../utils/constants.ts");

  console.log("Parsing CSS variables from globals.css...");
  const variables = parseCssVariables(cssPath);

  console.log(`Found ${Object.keys(variables).length} CSS variables`);

  console.log("Generating constants.ts...");
  generateConstantsFile(variables, outputPath);
}

if (require.main === module) {
  main();
}

export { main };

