// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordion_demo: dynamic(() => import("./AccordionDemo")),
  code_block: dynamic(() => import("./CodeBlock")),
  hero_card: dynamic(() => import("./HeroCard")),
  text_block: dynamic(() => import("./TextBlock")),
};
