// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  footer_column: dynamic(() => import("./FooterColumn")),
  hero_banner: dynamic(() => import("./HeroBanner")),
  image_text_block: dynamic(() => import("./ImageTextBlock")),
  intro_banner: dynamic(() => import("./IntroBanner")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  text_block: dynamic(() => import("./TextBlock")),
};
