// This file is auto-generated by a script that scans the registry directory.
// Do not manually modify this file.

export const registryTags = [
  // ui
  "accordion",
  "alert",
  "button",
  "form",
  // hooks
  "use-dynamic-form",
  // utils
  "web-validation"
] as const;

export type RegistryTag = (typeof registryTags)[number];
