#!/usr/bin/env node
/**
 * Generic preflight — generated by @aura-design/cli `blueprint`.
 * Checks Node (optional .nvmrc), pnpm, Prisma (if schema present), optional Postgres connectivity.
 */

import { readFileSync, existsSync } from "fs";
import { resolve } from "path";
import { execSync } from "child_process";

const colors = {
  reset: "\x1b[0m",
  bright: "\x1b[1m",
  red: "\x1b[31m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  blue: "\x1b[34m",
  cyan: "\x1b[36m",
};

interface CheckResult {
  success: boolean;
  message: string;
  details?: string;
}

function loadEnvFile(path: string): void {
  if (!existsSync(path)) return;
  const raw = readFileSync(path, "utf-8");
  for (const line of raw.split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const eq = t.indexOf("=");
    if (eq <= 0) continue;
    const key = t.slice(0, eq).trim();
    let val = t.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    if (!(key in process.env)) {
      process.env[key] = val;
    }
  }
}

const root = process.cwd();
loadEnvFile(resolve(root, ".env"));
loadEnvFile(resolve(root, ".env.local"));

function printResult(name: string, result: CheckResult) {
  const icon = result.success ? "✓" : "✗";
  const color = result.success ? colors.green : colors.red;
  console.log(`${color}${icon}${colors.reset} ${colors.bright}${name}${colors.reset}`);
  console.log(`  ${result.message}`);
  if (result.details) {
    console.log(`  ${colors.cyan}${result.details}${colors.reset}`);
  }
  console.log();
}

function checkNodeVersion(): CheckResult {
  try {
    const nvmrcPath = resolve(root, ".nvmrc");
    if (!existsSync(nvmrcPath)) {
      return {
        success: true,
        message: "No .nvmrc found",
        details: "Skipping Node version pin",
      };
    }
    const expectedVersion = readFileSync(nvmrcPath, "utf-8")
      .trim()
      .replace(/^v/, "");
    const currentVersion = process.version.replace(/^v/, "");
    const [expectedMajor, expectedMinor] = expectedVersion.split(".").map(Number);
    const [currentMajor, currentMinor] = currentVersion.split(".").map(Number);

    if (currentMajor === expectedMajor && currentMinor >= expectedMinor) {
      return {
        success: true,
        message: "Node.js version is compatible",
        details: `Current: v${currentVersion} | Expected: v${expectedVersion}`,
      };
    }
    if (currentMajor > expectedMajor) {
      return {
        success: true,
        message: "Node.js version is newer (should work)",
        details: `Current: v${currentVersion} | Expected: v${expectedVersion}`,
      };
    }
    return {
      success: false,
      message: "Node.js version mismatch",
      details: `Current: v${currentVersion} | Expected: v${expectedVersion}`,
    };
  } catch (error) {
    return {
      success: false,
      message: "Failed to check Node.js version",
      details: error instanceof Error ? error.message : String(error),
    };
  }
}

function checkPnpm(): CheckResult {
  try {
    const version = execSync("pnpm --version", { encoding: "utf-8" }).trim();
    try {
      const packageJson = JSON.parse(
        readFileSync(resolve(root, "package.json"), "utf-8"),
      );
      const packageManager = packageJson.packageManager || "";
      const expectedVersionMatch = packageManager.match(/pnpm@([\d.]+)/);
      if (expectedVersionMatch) {
        return {
          success: true,
          message: "pnpm is installed",
          details: `Current: v${version} | Expected: v${expectedVersionMatch[1]}`,
        };
      }
    } catch {
      /* ignore */
    }
    return {
      success: true,
      message: "pnpm is installed",
      details: `Version: v${version}`,
    };
  } catch {
    return {
      success: false,
      message: "pnpm is not installed",
      details: "Install it with: npm install -g pnpm",
    };
  }
}

function defaultPrismaClientPaths(): string[] {
  return [
    resolve(root, "node_modules/.prisma/client/index.js"),
    resolve(root, "node_modules/.prisma/client/default.js"),
    resolve(root, "node_modules/@prisma/client/index.js"),
  ];
}

function checkPrisma(): CheckResult {
  const schemaPath = resolve(root, "prisma", "schema.prisma");
  if (!existsSync(schemaPath)) {
    return {
      success: true,
      message: "No Prisma schema",
      details: "Skipping Prisma checks",
    };
  }

  try {
    execSync("npx prisma validate", {
      cwd: root,
      stdio: "pipe",
      encoding: "utf-8",
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return {
      success: false,
      message: "Prisma schema validation failed",
      details: msg,
    };
  }

  const found = defaultPrismaClientPaths().some((p) => existsSync(p));
  if (!found) {
    return {
      success: true,
      message: "Prisma schema is valid",
      details:
        "npx prisma validate passed — no default client under node_modules/.prisma or @prisma/client (custom generator output? run your generate script)",
    };
  }

  return {
    success: true,
    message: "Prisma schema is valid and default client is present",
    details: "npx prisma validate passed",
  };
}

async function checkDatabase(): Promise<CheckResult> {
  const url = process.env.DATABASE_URL?.trim();
  if (!url) {
    return {
      success: true,
      message: "DATABASE_URL not set",
      details: "Skipping database connection check",
    };
  }
  if (!url.startsWith("postgresql://") && !url.startsWith("postgres://")) {
    return {
      success: true,
      message: "Non-Postgres DATABASE_URL",
      details: "Skipping TCP connection test",
    };
  }

  try {
    const { Client } = await import("pg");
    const client = new Client({ connectionString: url });
    await client.connect();
    await client.query("SELECT 1");
    await client.end();
    return {
      success: true,
      message: "Database connection OK",
      details: "SELECT 1 succeeded via pg",
    };
  } catch (e) {
    const err = e as { code?: string };
    if (err?.code === "MODULE_NOT_FOUND") {
      return {
        success: true,
        message: "pg not installed",
        details:
          "Skipping DB check — add devDependency `pg` to enable connection verification",
      };
    }
    return {
      success: false,
      message: "Database connection failed",
      details: e instanceof Error ? e.message : String(e),
    };
  }
}

async function runPreflightChecks() {
  console.log(
    `\n${colors.bright}${colors.blue}Running preflight${colors.reset}\n`,
  );
  console.log(`${colors.cyan}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${colors.reset}\n`);

  const results: CheckResult[] = [];

  const nodeResult = checkNodeVersion();
  printResult("Node.js version", nodeResult);
  results.push(nodeResult);

  const pnpmResult = checkPnpm();
  printResult("pnpm", pnpmResult);
  results.push(pnpmResult);

  const prismaResult = checkPrisma();
  printResult("Prisma", prismaResult);
  results.push(prismaResult);

  const dbResult = await checkDatabase();
  printResult("Database", dbResult);
  results.push(dbResult);

  console.log(`${colors.cyan}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${colors.reset}\n`);

  const successCount = results.filter((r) => r.success).length;
  const totalCount = results.length;

  if (successCount === totalCount) {
    console.log(
      `${colors.green}${colors.bright}All checks passed (${successCount}/${totalCount})${colors.reset}\n`,
    );
    process.exit(0);
  } else {
    console.log(
      `${colors.red}${colors.bright}Some checks failed (${successCount}/${totalCount})${colors.reset}\n`,
    );
    process.exit(1);
  }
}

process.on("unhandledRejection", (error) => {
  console.error(`${colors.red}Unhandled error:${colors.reset}`, error);
  process.exit(1);
});

runPreflightChecks().catch((error) => {
  console.error(`${colors.red}Fatal error:${colors.reset}`, error);
  process.exit(1);
});
