// This file holds the main code for plugins. Code in this file has access to
// the *figma document* via the figma global object.
// You can access browser APIs in the <script> tag inside "ui.html" which has a
// full browser environment (See https://www.figma.com/plugin-docs/how-plugins-run).

// This file is auto-generated by scripts/generate-button-code.ts
// Do not edit manually. Run the script to regenerate.

// Color helpers
function hexToRgb(hex: string): { r: number; g: number; b: number } | null {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? {
        r: parseInt(result[1], 16) / 255,
        g: parseInt(result[2], 16) / 255,
        b: parseInt(result[3], 16) / 255,
      }
    : null;
}

// Button style configurations
const buttonStyles: Record<string, any> = {
  default: {
    bg: hexToRgb("#bf91ec"),
    text: hexToRgb("#ffffff"),
    hover: hexToRgb("#cea0fc"),
  },
  fill: {
    bg: hexToRgb("#bf91ec"),
    text: hexToRgb("#ffffff"),
    hover: hexToRgb("#cea0fc"),
  },
  pill: {
    bg: null, // transparent
    text: hexToRgb("#121b48"),
    border: hexToRgb("#121b48"),
    hover: hexToRgb("#1c1524"),
  },
  link: {
    bg: null, // transparent
    text: hexToRgb("#121b48"),
    hover: hexToRgb("#1c1524"),
  },
  menu: {
    bg: null, // transparent
    text: hexToRgb("#e9dbf9"),
  },
};

// Size configurations (height in pixels)
const sizeConfig: Record<string, number> = {
  default: 52, // calc(var(--aura) * 4) = 52px
  xs: 32.5, // calc(var(--aura) * 2.5) = 32.5px
  sm: 39, // calc(var(--aura) * 3) = 39px
  md: 52, // calc(var(--aura) * 4) = 52px
  lg: 65, // calc(var(--aura) * 5) = 65px
  xl: 78, // calc(var(--aura) * 6) = 78px
  icon: 39, // calc(var(--aura) * 3) = 39px
};

// Async function to generate buttons with different variants and states
async function generateButtons() {
  const variants = ["default","fill","pill","link","menu"];
  const sizes = ["default","xs","sm","md","lg","xl","icon"];
  const states = ["Default","Hover","Pressed"];

  // Load font first
  await figma.loadFontAsync({ family: "Inter", style: "Regular" });

  const buttons: FrameNode[] = [];
  const buttonSpacing = 100;

  variants.forEach((variant, vIdx) => {
    sizes.forEach((size, sIdx) => {
      states.forEach((state, stIdx) => {
        const style = buttonStyles[variant as keyof typeof buttonStyles];
        if (!style) return;

        // Create Frame (The Button)
        const button = figma.createFrame();
        button.name = `Button / ${variant} / ${size} / ${state}`;
        button.layoutMode = "HORIZONTAL";
        button.paddingLeft = 26;
        button.paddingRight = 26;
        button.paddingTop = 0;
        button.paddingBottom = 0;
        button.cornerRadius = 6.5;
        button.itemSpacing = 8;

        // Set height based on size
        const height = sizeConfig[size] || sizeConfig.default;
        // Set a default width that will accommodate the text (auto layout will adjust)
        button.resize(300, height);
        button.primaryAxisAlignItems = "CENTER";
        button.counterAxisAlignItems = "CENTER";

        // Apply background color
        if (style.bg) {
          const fills = JSON.parse(JSON.stringify(button.fills));
          fills[0] = { type: 'SOLID', color: style.bg };
          
          if (state === 'Hover' && style.hover) {
            fills[0].color = style.hover;
          } else if (state === 'Pressed') {
            // Darken for pressed state
            fills[0].color = {
              r: Math.max(0, style.bg.r * 0.7),
              g: Math.max(0, style.bg.g * 0.7),
              b: Math.max(0, style.bg.b * 0.7),
            };
          }
          button.fills = fills;
        } else {
          // Transparent background - add subtle background for hover/pressed states
          if (state === 'Hover' && style.hover) {
            // Add subtle background tint for hover
            const hoverColor = style.hover;
            button.fills = [{ 
              type: 'SOLID', 
              color: hoverColor,
              opacity: 0.1 
            }];
          } else if (state === 'Pressed') {
            // Add more visible background for pressed
            const pressedColor = style.hover || style.text;
            button.fills = [{ 
              type: 'SOLID', 
              color: pressedColor,
              opacity: 0.2 
            }];
          } else {
            button.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 }, opacity: 0 }];
          }
        }

        // Apply border
        if (variant === 'pill' && style.border) {
          button.strokes = [{ type: 'SOLID', color: style.border }];
          button.strokeWeight = 2;
        } else if (variant === 'fill' && style.bg) {
          button.strokes = [{ type: 'SOLID', color: style.bg }];
          button.strokeWeight = 2;
        } else {
          button.strokes = [];
        }

        // Create Text
        const text = figma.createText();
        text.characters = `${variant} ${size} ${state}`;
        
        let textColor = style.text;
        if (state === 'Hover' && style.hover && variant === 'link') {
          // For link variant, hover changes text color
          textColor = style.hover;
        }
        
        text.fills = [{ type: 'SOLID', color: textColor }];
        
        // Set font size based on button height
        const fontSize = Math.max(12, Math.floor(height * 0.4));
        text.fontSize = fontSize;
        
        button.appendChild(text);

        // Append to page first so layout is calculated
        figma.currentPage.appendChild(button);
        buttons.push(button);
      });
    });
  });

  // Position buttons after all are created and layout is calculated
  let maxWidth = 0;
  let maxHeight = 0;
  buttons.forEach(button => {
    if (button.width > maxWidth) maxWidth = button.width;
    if (button.height > maxHeight) maxHeight = button.height;
  });

  let currentX = 0;
  let currentY = 0;
  let rowHeight = 0;

  variants.forEach((variant, vIdx) => {
    sizes.forEach((size, sIdx) => {
      states.forEach((state, stIdx) => {
        const buttonIndex = vIdx * sizes.length * states.length + sIdx * states.length + stIdx;
        const button = buttons[buttonIndex];
        if (!button) return;

        button.x = currentX;
        button.y = currentY;
        
        currentX += maxWidth + buttonSpacing;
        rowHeight = Math.max(rowHeight, button.height);

        // Move to next row after all states for a size
        if (stIdx === states.length - 1) {
          currentX = 0;
          currentY += rowHeight + buttonSpacing;
          rowHeight = 0;
        }
      });
    });
    
    // Add extra spacing between variants
    if (vIdx < variants.length - 1) {
      currentY += buttonSpacing;
    }
  });

  figma.viewport.scrollAndZoomIntoView(figma.currentPage.children);
}

// Runs this code if the plugin is run in Figma
if (figma.editorType === 'figma') {
  generateButtons().then(() => {
    // Make sure to close the plugin when you're done. Otherwise the plugin will
    // keep running, which shows the cancel button at the bottom of the screen.
    figma.closePlugin();
  });
}

// Runs this code if the plugin is run in FigJam
if (figma.editorType === 'figjam') {
  // This plugin creates shapes and connectors on the screen.
  const numberOfShapes = 5;

  const nodes: SceneNode[] = [];
  for (let i = 0; i < numberOfShapes; i++) {
    const shape = figma.createShapeWithText();
    // You can set shapeType to one of: 'SQUARE' | 'ELLIPSE' | 'ROUNDED_RECTANGLE' | 'DIAMOND' | 'TRIANGLE_UP' | 'TRIANGLE_DOWN' | 'PARALLELOGRAM_RIGHT' | 'PARALLELOGRAM_LEFT'
    shape.shapeType = 'ROUNDED_RECTANGLE';
    shape.x = i * (shape.width + 200);
    shape.fills = [{ type: 'SOLID', color: { r: 1, g: 0.5, b: 0 } }];
    figma.currentPage.appendChild(shape);
    nodes.push(shape);
  }

  for (let i = 0; i < numberOfShapes - 1; i++) {
    const connector = figma.createConnector();
    connector.strokeWeight = 8;

    connector.connectorStart = {
      endpointNodeId: nodes[i].id,
      magnet: 'AUTO',
    };

    connector.connectorEnd = {
      endpointNodeId: nodes[i + 1].id,
      magnet: 'AUTO',
    };
  }

  figma.currentPage.selection = nodes;
  figma.viewport.scrollAndZoomIntoView(nodes);

  // Make sure to close the plugin when you're done. Otherwise the plugin will
  // keep running, which shows the cancel button at the bottom of the screen.
  figma.closePlugin();
}
