// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  footer_column: dynamic(() => import("./FooterColumn")),
  navigation_item: dynamic(() => import("./NavigationItem")),
};
