// Code generated by Slice Machine. DO NOT EDIT.

import SectionGridCards from './SectionGridCards';
import SectionHeading from './SectionHeading';

export {
	SectionGridCards,
	SectionHeading,
};

export const components = {
	section_grid_cards: SectionGridCards,
	hero_section_split: SectionHeading,
};
