// Code generated by Slice Machine. DO NOT EDIT.

import Iframe from './Iframe';
import TableBlock from './TableBlock';

export {
	Iframe,
	TableBlock,
};

export const components = {
	iframe: Iframe,
	table_block: TableBlock,
};
