import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PrismicPreview } from "@prismicio/next";
import { repositoryName } from "@/prismicio";

import "@/app/global.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Nprogress from "@/components/ui/Nprocess";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>
          <div className="page-pancake">
            <Header />
            <div>{children}</div>
            <Footer />
          </div>
          <PrismicPreview repositoryName={repositoryName} />
        </main>
        <Nprogress />
      </body>
    </html>
  );
}
