import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@aura-design/system/main.css"

import Footer from "@/components/Footer";
import Header from "@/components/Header";

import "@/styles/globals.css";
import "@/styles/main.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>
          <div className="page-pancake">
            <Header />
            <div>{children}</div>
            <Footer />
          </div>
        </main>
      </body>
    </html>
  );
}
